{% set name = "marslab" %}
{% set version = "0.9.24" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/marslab-{{ version }}.tar.gz
  sha256: e2a7bd34289adf5b5caa4ede720a8f26b6c7c00932889d72842defe323578ac4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - astropy-base
    - cytoolz
    - dustgoggles
    - fast-histogram
    - matplotlib-base
    - more-itertools
    - numpy
    - opencv
    - pandas
    - pathos
    - pdr
    - pip
    - python-dateutil
    - scikit-image
    - scipy
    - sympy
    # optional dependencies for testing, included by default
    - pytest
    - hypothesis

test:
  imports:
    - marslab
  commands:
    - pip check
  requires:
    - pip
    - setuptools

about:
  home: https://github.com/millionconcepts/marslab
  summary: Utilities for working with observational data of Mars.
  description: |
    marslab is the core support library for the marslab ecosystem (https://github.com/MillionConcepts/marslab-reference).
    It defines common formats, shared references, and support objects, many of which are also useful on their own.
    Highlights include Look, a lightweight construction kit for multispectral visualizations;
    and BandSet, an object that streamlines operations on multispectral observations, treating entire clusters of related images as coherent wholes.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Sierra-MC
    - m-stclair
