{% set name = "marslab" %}
{% set version = "0.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/marslab-{{ version }}.tar.gz
  sha256: 55ddf1ea959ca93dafc4c48340a4e54dbd83d1e1d909ef63ee56534c66e9c3db

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python>=3.9
    - astropy
    - cytoolz
    - dustgoggles
    - fast-histogram
    - matplotlib
    - more-itertools
    - numpy
    - opencv
    - pandas
    - pathos
    - pdr
    - pip
    - python-dateutil
    - scikit-image
    - scipy
    - sympy
    # optional dependencies for testing, included by default
    - pytest
    - hypothesis

test:
  imports:
    - marslab
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/millionconcepts/marslab
  summary: Utilities for working with observational data of Mars.
  description: |
    marslab is the core support library for the marslab ecosystem (https://github.com/MillionConcepts/marslab-reference).
    It defines common formats, shared references, and support objects, many of which are also useful on their own.
    Highlights include Look, a lightweight construction kit for multispectral visualizations;
    and BandSet, an object that streamlines operations on multispectral observations, treating entire clusters of related images as coherent wholes.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Sierra-MC
    - m-stclair
